### ISSUE TITLE
Error with npm library @slack/bolt

### ISSUE THREAD

**Issue by evanyang1** [hackforla/VRMS#1052]
### Overview
I'm getting an error when I run `npm run start`

`Error: An API error occurred: account_inactive
[0]     at Object.platformErrorFromResult (/home/evanyang/Desktop/VRMS/backend/node_modules/@slack/web-api/dist/errors.js:51:33)
[0]     at WebClient.apiCall (/home/evanyang/Desktop/VRMS/backend/node_modules/@slack/web-api/dist/WebClient.js:152:28)
[0]     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[0]   code: 'slack_webapi_platform_error',
[0]   data: { ok: false, error: 'account_inactive', response_metadata: {} }
[0] }`

The problem is triggered in the code in the node module, and I believe the issue may have something to do with `VRMS/backend/routers/slack.router.js`

### Action Items
- [ ] Research the error
- [ ] fix the code - or find an active account - so the error no longer appears

### Acceptance Criteria
- [ ] The above error no longer comes up when 

### Resources/Instructions
/backend/routers/slack.router.js

**Comment by drubgrubby** [comment]
This error is fixed in PR #1067
