### ISSUE TITLE
Resolve test suite configuration failure

### ISSUE THREAD

**Issue by trillium** [hackforla/VRMS#1487]
### Overview
While working on an unrelated PR one of the tests failed. Pushing back up again 15m later resolved the issue, but tests shouldn't sometimes fail.

### Action Items
Take a look at the error blob below and figure out why this test might sometimes fail.
```
FAIL routers/events.router.test.js
  ● READ › GET Event by ID

    expect(received).toBe(expected) // Object.is equality

    Expected: "64ec225b[41](https://github.com/hackforla/VRMS/actions/runs/5995586790/job/16258833574#step:6:42)eeef001d27d73a"
    Received: undefined

       96 |     expect(response.statusCode).toBe(200);
       97 |     const apiRetrievedEvent = await response.body;
    >  98 |     expect(apiRetrievedEvent._id).toBe(dbCreatedeventId);
          |                                   ^
       99 | 
      100 |     done();
      101 |   });

      at Object.<anonymous> (routers/events.router.test.js:98:35)
          at runMicrotasks (<anonymous>)

POST /api/events/ 201 11.914 ms - 164
```
- [ ] Investigate updating dependency of MongoDB in memory database.
- [ ] Add findings to this issue in a comment. 
- [ ] Create a test that confirms the backend test environment has initialized properly. 

### Resources

@plang-psm says 

> When we did an audit on the cron job for the events, we realized it causes a lot of random issue every time it fetches for events

**Comment by JackHaeg** [comment]
@trillium is working on a version of the test suite where all of the failing tests are disabled, and then we will re-enable each one and solve it individually. Feel free to continue working on this, just wanted to give an update on what our future plans are for the test environment.

**Comment by JackHaeg** [comment]
**Hi @dannyprikaz! When you have a moment, can you please provide an update with the following information:**
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."
  - remember to add links to the top of the issue if they are going to be needed again.

**Comment by dannyprikaz** [comment]
Hey @JackHaeg. Thanks for checking in.

1. Progress: I have found the test that failed intermittently and worked out what functionality it is meant to test. I've set breakpoints and debugged the test to check the value of various variables. I don't yet understand any reason why the test failed at one point.
2. Blockers: I don't fully understand why we are creating and stopping Mongo Servers for every test suite. I would recommend mocking all of that functionality in unit tests, but I want to get some guidance on this.
3. Availability: I can spend about 3 hours on this this week.
4. ETA: Now that I've investigated the issue and gotten a better understanding of the test itself, I think I need a better understanding of what the team wants to happen next before I can give an ETA.
5.  Pictures or Links: N/A

**Comment by JackHaeg** [comment]
- @dannyprikaz proposed a new way of working on this issue, and will create a new epic and set of issues that follow his proposed approach along with @JackHaeg.
- After these issues have been drafted & prioritized, we will then un-assign this issue, and place it in the icebox, with the new epic serving as the dependency.

**Comment by dannyprikaz** [comment]
I encountered another intermittent failure:

```
 FAIL  models/user.test.js (5.349 s)
  ● Question Model saves the correct values › Create a simple user

    TypeError: Cannot read properties of undefined (reading 'name')

      52 |     const savedDataArray = await User.find();
      53 |     const savedData = savedDataArray[0];
    > 54 |     expect(savedData.name.firstName).toBe(submittedData.name.firstName);
         |                      ^
      55 |     expect(savedData.currentRole).toBe(submittedData.currentRole);
      56 |     expect(savedData.desiredJobTitle).toBe(submittedData.desiredJobTitle);
      57 |     done();

      at Object.<anonymous> (models/user.test.js:54:22)
      at processTicksAndRejections (node:internal/process/task_queues:105:5)
```

It seems like a similar issue, where for some reason the document isn't created or retrieved properly, but when I ran the tests a few moments later, everything worked as it should.

For the Epic we're talking about, I want to make all of our current tests look more like unit tests (with behavior isolated to just the class being tested), but I think that we will want some integration tests that resemble what we currently have, and at that point, we will need to figure out what's causing this to fail intermittently.

**Comment by JackHaeg** [comment]
Leaving issue open, @dannyprikaz is continuing to look into resolving the test suite configuration failure, given that the following PR did not resolve all of the issues: https://github.com/hackforla/VRMS/pull/1876

**Comment by dannyprikaz** [comment]
> I encountered another intermittent failure:
> 
> ```
>  FAIL  models/user.test.js (5.349 s)
>   ● Question Model saves the correct values › Create a simple user
> 
>     TypeError: Cannot read properties of undefined (reading 'name')
> 
>       52 |     const savedDataArray = await User.find();
>       53 |     const savedData = savedDataArray[0];
>     > 54 |     expect(savedData.name.firstName).toBe(submittedData.name.firstName);
>          |                      ^
>       55 |     expect(savedData.currentRole).toBe(submittedData.currentRole);
>       56 |     expect(savedData.desiredJobTitle).toBe(submittedData.desiredJobTitle);
>       57 |     done();
> 
>       at Object.<anonymous> (models/user.test.js:54:22)
>       at processTicksAndRejections (node:internal/process/task_queues:105:5)
> ```
> 
> It seems like a similar issue, where for some reason the document isn't created or retrieved properly, but when I ran the tests a few moments later, everything worked as it should.
> 
> For the Epic we're talking about, I want to make all of our current tests look more like unit tests (with behavior isolated to just the class being tested), but I think that we will want some integration tests that resemble what we currently have, and at that point, we will need to figure out what's causing this to fail intermittently.

Update: Because this specific test failed once, it really cuts down on the avenues that still need to be explored. Trillium's failed test was one that followed the behavior of multiple components.  In `models/user.test.js` there are really only three possible culprits.

1. `user.test.js` or `user.model.js` If there's something wrong with one of these files, it could be the source of an intermittent failure. This seems unlikely to me, because no error in either of those files could have caused the intermittent failure that Trillium observed.
2. `setup-test.js` This file runs the logic that spins up test Mongo servers. It is the only other file besides `user.model.js` that `user.test.js` touches. This setup file is used by all of the integration-like test-suites. If there's a problem with it, that could explain how it's causing random failures in random tests. I don't know what the issue is with this file though. It seems to be handling asynchronous code appropriately. There are some tests that are using the same database name as other tests, but not the one that produced Trillium's failure. That's probably not the issue.
3. `MongoMemoryServer` In the README file, it says that we have opted to use in memory test databases "To maintain idempotent tests." I'm sure that they people who made that decision new what they were doing, but it's possible that MongoMemoryServer is just not behaving as expected. It's supposed to choose a free port for each new server, but maybe sometimes that port number is colliding and collections are being dumped while they are being used in other tests. I have noticed a filed `globalConfig.json` that has a `mongoUri` field in it that changes every time I run tests. That's something else to look into as an indicator toward the source of the error.

**Comment by dannyprikaz** [comment]
More updates:

### First, we have another intermittent error to document:

```
 FAIL  routers/auth.router.test.js (5.254 s)
  ● SIGNIN User › User can signin and returns 200
                                                                                                                                                                                     
    MongoError: E11000 duplicate key error dup key: { : "test@test.com" }                                                                                                            
                                                                                                                                                                                     
      at Function.create (node_modules/mongodb/lib/core/error.js:57:12)                                                                                                              
      at toError (node_modules/mongodb/lib/utils.js:123:22)                                                                                                                          
      at node_modules/mongodb/lib/operations/common_functions.js:265:39                                                                                                              
      at handler (node_modules/mongodb/lib/core/sdam/topology.js:942:24)                                                                                                             
      at node_modules/mongodb/lib/cmap/connection_pool.js:350:13                                                                                                                     
      at handleOperationResult (node_modules/mongodb/lib/core/sdam/server.js:558:5)                                                                                                  
      at MessageStream.messageHandler (node_modules/mongodb/lib/cmap/connection.js:277:5)                                                                                            
      at MessageStream.emit (node:events:524:28)                                                                                                                                     
      at processIncomingData (node_modules/mongodb/lib/cmap/message_stream.js:144:12)                                                                                                
      at MessageStream._write (node_modules/mongodb/lib/cmap/message_stream.js:42:5)
      at writeOrBuffer (node:internal/streams/writable:572:12)
      at _write (node:internal/streams/writable:501:10)
      at MessageStream.Writable.write (node:internal/streams/writable:510:10)
      at Socket.ondata (node:internal/streams/readable:1009:22)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
```

Looking at this failure, [this is what I found out about that error code](https://medium.com/@roshan.waa/troubleshooting-mongoerror-e11000-duplicate-key-error-in-mongodb-with-javascript-example-1c3ff25b6fd2#:~:text=If%20you're%20working%20with,field%2C%20which%20causes%20a%20conflict.). That tells me that the collections that `auth.model.js` accesses aren't being cleared between tests every time. It's just a tough issue to reproduce.

They really should be getting cleared out because `setup-test.js` calls this function in the `afterEach` block:

```
async function removeAllCollections() {
  const mongooseCollections = mongoose.connection.collections;
  const collections = Object.keys(mongooseCollections);
  for (const collectionName of collections) {
    const collection = mongoose.connection.collections[collectionName];
    collection.deleteMany();
  }
}
```

### Second: I figured out where that `globalConfig.json` file was coming from.

In our `jest.config.js` file, we have a line like this: `preset: '@shelf/jest-mongodb',`. That line tells jest to use a bunch of setup configurations from the package [`@shelf/jest-mongodb`](preset: '@shelf/jest-mongodb',). That link has more information about the package, but to summarize, it does the same thing that we have been doing in `setup-test.js`. It was spinning up a `MongodbMemoryServer` for each test that we were then never connecting to because we were making and connecting to a separate `MongoMemoryServer` (imported from the same package `mongodb-memory-server`, not sure why the variable name is different). `@shelf/jest-mongodb` then stores the MongoUri in `globalconfig.json`.

Since we had that preset to work with, I tried running the tests connecting to that Mongo server instead, but the tests failed much more erratically. I then tried removing the preset, and other files that go with it. Everything works fine, but it was while I was running `npm test` several times in the `backend` directory that I got the error above. So removing the preset doesn't eliminate our issue, but it does take away one variable.

**Comment by dannyprikaz** [comment]
I think I have a solution to this problem. I still can't explain why the collections are not always being cleared they way they are supposed to be, but I think we can just rewrite our integration tests in such a way that we don't need to reset the state of the database between each test. We could write our integration tests like a narrative such that each test interacts with the database in the state that it's left in by the previous test. 

For example when we're testing the functionality around users, we can write one test that creates a user. Then we can write a separate test the gets that user by its ID. Then update and delete that same user in subsequent tests.

**Comment by dannyprikaz** [comment]
Another one:

```
 FAIL  routers/auth.router.test.js (5.854 s)
  ● CREATE User › Create user with POST to /auth/signup                                                                                                                              
                                                                                                                                                                                     
    expect(received).toBe(expected) // Object.is equality                                                                                                                            
                                                                                                                                                                                     
    Expected: 201                                                                                                                                                                    
    Received: 400                                                                                                                                                                    
                                                                                                                                                                                     
      70 |       .set(headers);                                                                                                                                                      
      71 |                                                                                                                                                                           
    > 72 |     expect(res.status).toBe(201);                                                                                                                                         
         |                        ^                                                                                                                                                  
      73 |   });                                                                                                                                                                     
      74 | });
      75 |

      at Object.<anonymous> (routers/auth.router.test.js:72:24)
      at processTicksAndRejections (node:internal/process/task_queues:105:5)
```

**Comment by JackHaeg** [comment]
Per @dannyprikaz we can close this issue once #1947 is merged: 

> I think that we can close [#1487](https://github.com/hackforla/VRMS/issues/1487) once we merge [#1947](https://github.com/hackforla/VRMS/pull/1947). That gets rid of all of the remaining tests that were using setupDB, so all of the intermittent failures should be gone. In addition, I have created [#1950](https://github.com/hackforla/VRMS/issues/1950) as an epic for writing new unit tests for models, and [#1951](https://github.com/hackforla/VRMS/issues/1951) is an example of one of its sub-issues.
> I've added some sub issues to [#1899] for creating integration tests, and I have submitted a [PR] for [#1935] that people can look to as an example for writing integration tests.
> We still need an epic issue for fixing the controller unit tests, but then I think we've got all of our issues set up.

**Comment by trillium** [comment]
Closed as completed as per @dannyprikaz
